---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: kibana
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - name: 9405tcp
      port: 9405
      targetPort: 9405
      protocol: TCP
