---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - name: 9200tcp
      port: 9200
      targetPort: 9200
      protocol: TCP
