---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  ports:
    - name: 9200tcp
      port: 9200
      targetPort: 9200
      protocol: TCP
