---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: apigateway
spec:
  selector:
    app: apigateway
  type: NodePort
  ports:
    - name: http1
      port: 5555
      targetPort: 5555
      protocol: TCP
    - name: http2
      port: 5480
      targetPort: 5480
      protocol: TCP
    - name: http3
      port: 9072
      targetPort: 9072
      protocol: TCP
    - name: https1
      port: 5443
      targetPort: 5443
      protocol: TCP
    - name: https2
      port: 5543
      targetPort: 5543
      protocol: TCP
